#!/bin/sh

BUILD_DIR=/home/josepht/junk/bash
PATTERN="bash_4.2-5ubuntu"

if [ -z "$JUJU_ENV" ]; then
	echo "You need to have your juju environment setup first."
	exit 1
fi

WEBUI_HOST=$(juju status ci-airline-webui-apache/0 |
	grep public-address | sed 's/.*public-address: //' | sort -u | tail -1)
#echo "DEBUG: WEBUI_HOST: '$WEBUI_HOST'"

if [ ! -d "$BUILD_DIR" ]; then
	echo "Bad build directory: $BUILD_DIR"
	exit 1
fi

LAST_DIR=$(basename $(pwd))

if [ "$LAST_DIR" != "cli" ]; then
	echo "You need to be in a 'cli' directory"
	exit 1
fi

PREV_DIR=$(pwd)
cd $BUILD_DIR

rm -f "../$PATTERN*"; dch -i -D utopic test; debuild --no-tgz-check -S

VER=$(ls ../$PATTERN* | sed "s/.*${PATTERN}\([0-9]*\).*/\1/" | uniq | sort -n | tail -1)
#echo "DEBUG: VER: $VER"

#echo "DEBUG: PREV_DIR: $PREV_DIR"
cd $PREV_DIR &&
	sh -c "PYTHONPATH=../ci-utils python ubuntu-ci -u http://$WEBUI_HOST create_ticket -t 'bash 4.2-5ubuntu$VER' -c jat -d 'desc' -s $BUILD_DIR/../bash_4.2-5ubuntu${VER}_source.changes; VER=$(($VER + 1))"
