#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: $0 <unit-name>[/<unit-number>]"
	exit 1
fi
. $(dirname $0)/.j_rc

if [ -n "$UNIT" ]; then
	shift
	juju ssh ${PREFIX}$UNIT less /var/log/juju/unit*${PREFIX}${SERVICE}*.log
fi
